apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: service-tracker
spec:
  components:
    - componentName: tracker-postgres-db
      parameterValues:
        - name: dbuser
          value: dbuser
        - name: dbpassword
          value: dbpassword
        - name: database
          value: hackfest  
    - componentName: data-api
      parameterValues:
        - name: dbuser
          value: "dbuser"
        - name: dbpassword
          value: "dbpassword"
        - name: dbhostname
          value: "postgres.default.svc.cluster.local"
        - name: dbport
          value: "5432"
        - name: dbname
          value: "hackfest"  
        - name: dbdriver
          value: "postgres"
        - name: dboptions
          value: ""
    - componentName: flights-api
      parameterValues:
        - name: dataUri
          value: "http://data-api.default.svc.cluster.local:3009/"
      traits:
        - name: manual-scaler
          parameterValues:
            - name: replicaCount
              value: 2
    - componentName: quakes-api
      parameterValues:
        - name: dataUri
          value: "http://data-api.default.svc.cluster.local:3009/"  
      traits:
        - name: manual-scaler
          parameterValues:
            - name: replicaCount
              value: 2       
    - componentName: weather-api
      parameterValues:
        - name: dataUri
          value: "http://data-api.default.svc.cluster.local:3009/"
      traits:
        - name: manual-scaler
          parameterValues:
            - name: replicaCount
              value: 2        
    - componentName: service-tracker-ui
      parameterValues:
        - name: flightsUri
          value: "http://flights-api.default.svc.cluster.local:3003/"
        - name: weatherUri
          value: "http://weather-api.default.svc.cluster.local:3015/"
        - name: quakesUri
          value: "http://quakes-api.default.svc.cluster.local:3012/"
      traits:
        - name: ingress
          parameterValues:
            - name: hostname
              value: servicetracker.oam.io
            - name: path
              value: / 
            - name: service_port
              value: 8080