apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: knative-postgresql-appconfig
spec:
  components:
    - componentName: webapp
      dataInputs:
        - valueFrom:
            dataOutputName: alibaba-rdspostgresql-conn
          toFieldPaths:
            - spec.template.spec.containers[0].env[0].valueFrom.secretKeyRef.name
            - spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.name
            - spec.template.spec.containers[0].env[2].valueFrom.secretKeyRef.name

    - componentName: db
      dataOutputs:
        - name: alibaba-rdspostgresql-conn
          fieldPath: "spec.writeConnectionSecretToRef.name"
          conditions:
            - op: eq
              value: Running
              fieldPath: "status.atProvider.dbInstanceStatus"