apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: webapp
spec:
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Configuration
    metadata:
      name: webapp
      namespace: default
    spec:
      template:
        spec:
          containers:
            - image: oamdev/postgresql-flask-web-application:v0.1
              name: webapp
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: endpoint
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: password
              ports:
                - containerPort: 80
                  name: http1 # Must be one of "http1" or "h2c" (if supported). Defaults to "http1".
          timeoutSeconds: 600
